# Generated by Django 2.1.4 on 2019-12-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
