# Generated by Django 2.1.4 on 2019-12-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_question_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_status',
        ),
        migrations.AddField(
            model_name='question',
            name='question_solution',
            field=models.TextField(default='solution'),
        ),
    ]
